### ISSUE TITLE
How to disconnect from Storage::disk()

### ISSUE THREAD

**Issue by pndx** [thephpleague/flysystem#1433]
### Question

I use laravel Storage facade to create instance and try to disconnect. How can i disconnect?
I got some error info:
```
[2022-03-17 17:45:32] local.INFO: #0 /data/wwwroot/example.com/vendor/lea
gue/flysystem-ftp/FtpConnectionProvider.php(46): League\Flysystem\Ftp\UnableToConnectToFtpHost::forHost()#1 /data/wwwroot/example.com/vendor/league/flysystem-ftp/FtpConnectionPro
vider.php(22): League\Flysystem\Ftp\FtpConnectionProvider->createConnectionResource()#2 /data/wwwroot/example.com/vendor/league/flysystem-ftp/FtpAdapter.php(1
17): League\Flysystem\Ftp\FtpConnectionProvider->createConnection()#3 /data/wwwroot/example.com/vendor/league/flysystem-ftp/FtpAdapter.php(6
61): League\Flysystem\Ftp\FtpAdapter->connection()#4 /data/wwwroot/example.com/vendor/league/flysystem-ftp/FtpAdapter.php(3
45): League\Flysystem\Ftp\FtpAdapter->prefixer()#5 /data/wwwroot/example.com/vendor/league/flysystem-ftp/FtpAdapter.php(1
48): League\Flysystem\Ftp\FtpAdapter->fileSize()#6 /data/wwwroot/example.com/vendor/league/flysystem/src/Filesystem.php(4
8): League\Flysystem\Ftp\FtpAdapter->fileExists()#7 /data/wwwroot/example.com/vendor/laravel/framework/src/Illuminate/File
system/FilesystemAdapter.php(159): League\Flysystem\Filesystem->has()#8 /data/wwwroot/examplej.com/vendor/laravel/framework/src/Illuminate/File
system/FilesystemAdapter.php(170): Illuminate\Filesystem\FilesystemAdapter->exists()#9 /data/wwwroot/example.com/app/Traits/GenerateHtml.php(25): Illuminate\
Filesystem\FilesystemAdapter->missing()#10 /data/wwwroot/example.com/app/Jobs/GenerateHtmlFromApiJob.php(34): Ap
p\Jobs\GenerateHtmlFromApiJob->generateHtml()#11 /data/wwwroot/example.com/vendor/laravel/framework/src/Illuminate/Con
tainer/BoundMethod.php(36): App\Jobs\GenerateHtmlFromApiJob->handle()#12 /data/wwwroot/example.com/vendor/laravel/framework/src/Illuminate/Con
tainer/Util.php(41): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()#13 /data/wwwroot/example.com/vendor/laravel/framework/src/Illuminate/Con
tainer/BoundMethod.php(93): Illuminate\Container\Util::unwrapIfClosure()#14 /data/wwwroot/example.com/vendor/laravel/framework/src/Illuminate/Con
tainer/BoundMethod.php(37): Illuminate\Container\BoundMethod::callBoundMethod()#15 /data/wwwroot/example.com/vendor/laravel/framework/src/Illuminate/Con
tainer/Container.php(653): Illuminate\Container\BoundMethod::call()#16 /data/wwwroot/example.com/vendor/laravel/framework/src/Illuminate/Bus
/Dispatcher.php(128): Illuminate\Container\Container->call()#17 /data/wwwroot/example.com/vendor/laravel/framework/src/Illuminate/Pip
eline/Pipeline.php(128): Illuminate\Bus\Dispatcher->Illuminate\Bus\{closure}()#18 /data/wwwroot/example.com/vendor/laravel/framework/src/Illuminate/Pip
eline/Pipeline.php(103): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()#19 /data/wwwroot/example.com/vendor/laravel/framework/src/Illuminate/Bus
/Dispatcher.php(132): Illuminate\Pipeline\Pipeline->then()#20 /data/wwwroot/example.com/vendor/laravel/framework/src/Illuminate/Que
ue/CallQueuedHandler.php(119): Illuminate\Bus\Dispatcher->dispatchNow()#21 /data/wwwroot/example.com/vendor/laravel/framework/src/Illuminate/Pip
eline/Pipeline.php(128): Illuminate\Queue\CallQueuedHandler->Illuminate\Queue\{closure}()#22 /data/wwwroot/example.com/vendor/laravel/framework/src/Illuminate/Pip
eline/Pipeline.php(103): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()#23 /data/wwwroot/example.com/vendor/laravel/framework/src/Illuminate/Que
ue/CallQueuedHandler.php(121): Illuminate\Pipeline\Pipeline->then()#24 /data/wwwroot/example.com/vendor/laravel/framework/src/Illuminate/Que
ue/CallQueuedHandler.php(69): Illuminate\Queue\CallQueuedHandler->dispatchThroughMiddleware()#25 /data/wwwroot/example.com/vendor/laravel/framework/src/Illuminate/Que
ue/Jobs/Job.php(98): Illuminate\Queue\CallQueuedHandler->call()#26 /data/wwwroot/example.com/vendor/laravel/framework/src/Illuminate/Que
ue/Worker.php(428): Illuminate\Queue\Jobs\Job->fire()#27 /data/wwwroot/example.com/vendor/laravel/framework/src/Illuminate/Que
ue/Worker.php(378): Illuminate\Queue\Worker->process()#28 /data/wwwroot/example.com/vendor/laravel/framework/src/Illuminate/Que
ue/Worker.php(172): Illuminate\Queue\Worker->runJob()#29 /data/wwwroot/example.com/vendor/laravel/framework/src/Illuminate/Que
ue/Console/WorkCommand.php(126): Illuminate\Queue\Worker->daemon()#30 /data/wwwroot/example.com/vendor/laravel/framework/src/Illuminate/Que
ue/Console/WorkCommand.php(110): Illuminate\Queue\Console\WorkCommand->runWorker()#31 /data/wwwroot/example.com/vendor/laravel/horizon/src/Console/WorkComm
and.php(51): Illuminate\Queue\Console\WorkCommand->handle()#32 /data/wwwroot/example.com/vendor/laravel/framework/src/Illuminate/Con
tainer/BoundMethod.php(36): Laravel\Horizon\Console\WorkCommand->handle()#33 /data/wwwroot/example.com/vendor/laravel/framework/src/Illuminate/Con
tainer/Util.php(41): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()#34 /data/wwwroot/example.com/vendor/laravel/framework/src/Illuminate/Con
tainer/BoundMethod.php(93): Illuminate\Container\Util::unwrapIfClosure()#35 /data/wwwroot/example.com/vendor/laravel/framework/src/Illuminate/Con
tainer/BoundMethod.php(37): Illuminate\Container\BoundMethod::callBoundMethod()#36 /data/wwwroot/example.com/vendor/laravel/framework/src/Illuminate/Con
tainer/Container.php(653): Illuminate\Container\BoundMethod::call()#37 /data/wwwroot/example.com/vendor/laravel/framework/src/Illuminate/Con
sole/Command.php(136): Illuminate\Container\Container->call()#38 /data/wwwroot/example.com/vendor/symfony/console/Command/Command.php(
291): Illuminate\Console\Command->execute()#39 /data/wwwroot/example.com/vendor/laravel/framework/src/Illuminate/Con
sole/Command.php(121): Symfony\Component\Console\Command\Command->run()#40 /data/wwwroot/example.com/vendor/symfony/console/Application.php(989)
: Illuminate\Console\Command->run()#41 /data/wwwroot/example.com/vendor/symfony/console/Application.php(299)
: Symfony\Component\Console\Application->doRunCommand()#42 /data/wwwroot/example.com/vendor/symfony/console/Application.php(171)
: Symfony\Component\Console\Application->doRun()#43 /data/wwwroot/example.com/vendor/laravel/framework/src/Illuminate/Con
sole/Application.php(102): Symfony\Component\Console\Application->run()#44 /data/wwwroot/example.com/vendor/laravel/framework/src/Illuminate/Fou
ndation/Console/Kernel.php(129): Illuminate\Console\Application->run()#45 /data/wwwroot/example.com/artisan(37): Illuminate\Foundation\Console\
Kernel->handle()
```

**Comment by frankdejonge** [comment]
This is an exception that highlights a connection failure. I'm not sure I understand the question 😅
