### ISSUE TITLE
Sftp uploading randomly results in UnableToCreateDirectory

### ISSUE THREAD

**Issue by NilsSlui** [thephpleague/flysystem#1557]
PHP 8.1.9
Flysystem: v3.2.0
PHPSECLIB: v3.0.15
Flysystem-sftp-v3

Every day I run many jobs that deliver files to many different SFTP servers, however some deliveries fail with the exception UnableToCreateDirectory.

When trying to append to the file (looks like: sftp_foobar/files/acme-23-11-22.json) or when creating a new file it is sometimes indicated that it’s trying to create the directory sftp_foobar/files/ which in fact already exists. The function ensureParentDirectoryExists() in SftpAdapter.php thinks the folder does not exists seemingly at random. The only solution is to retry the job, which often works on the first try.

I checked the logs of the sftp server and it does not have any error messages regarding this. It seems like FlySystem comes to the conclusion the file/directory on the sftp server does not exist without actually communicating with the server about this file. 

Because this issue happens on multiple sftp servers I am fairly sure that it is an issue with flysystem, but I have so far been unable to solve this issue. 
```
League\Flysystem\UnableToCreateDirectory: Unable to create a directory at sftp_foobar/files.
#47 /vendor/league/flysystem/src/UnableToCreateDirectory.php(20): League\Flysystem\UnableToCreateDirectory::atLocation
#46 /vendor/league/flysystem-sftp-v3/SftpAdapter.php(137): League\Flysystem\PhpseclibV3\SftpAdapter::makeDirectory
#45 /vendor/league/flysystem-sftp-v3/SftpAdapter.php(120): League\Flysystem\PhpseclibV3\SftpAdapter::ensureParentDirectoryExists
#44 /vendor/league/flysystem-sftp-v3/SftpAdapter.php(97): League\Flysystem\PhpseclibV3\SftpAdapter::upload
#43 /vendor/league/flysystem-sftp-v3/SftpAdapter.php(144): League\Flysystem\PhpseclibV3\SftpAdapter::write
#42 /vendor/league/flysystem/src/Filesystem.php(56): League\Flysystem\Filesystem::write
#41 /vendor/laravel/framework/src/Illuminate/Filesystem/FilesystemAdapter.php(357): Illuminate\Filesystem\FilesystemAdapter::put
#40 /app/ExportSenders/InternalSftpSender.php(226): App\ExportSenders\InternalSftpSender::write
#39 /app/ExportSenders/InternalSftpSender.php(120): App\ExportSenders\InternalSftpSender::send
#38 /app/Service/ExportSenderService.php(29): App\Service\ExportSenderService::send
#37 /app/Jobs/Delivery/InstantDelivery.php(69): App\Jobs\Delivery\InstantDelivery::App\Jobs\Delivery\{closure}
#36 /vendor/laravel/framework/src/Illuminate/Cache/Lock.php(126): Illuminate\Cache\Lock::block
#35 /app/Jobs/Delivery/InstantDelivery.php(89): App\Jobs\Delivery\InstantDelivery::handle
#34 /vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}
#33 /vendor/laravel/framework/src/Illuminate/Container/Util.php(41): Illuminate\Container\Util::unwrapIfClosure
#32 /vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\Container\BoundMethod::callBoundMethod
#31 /vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\Container\BoundMethod::call
#30 /vendor/laravel/framework/src/Illuminate/Container/Container.php(651): Illuminate\Container\Container::call
#29 /vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(128): Illuminate\Bus\Dispatcher::Illuminate\Bus\{closure}
#28 /vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Illuminate\Pipeline\Pipeline::Illuminate\Pipeline\{closure}
#27 /vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\Pipeline\Pipeline::then
#26 /vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(132): Illuminate\Bus\Dispatcher::dispatchNow
#25 /vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(123): Illuminate\Queue\CallQueuedHandler::Illuminate\Queue\{closure}
#24 /vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Illuminate\Pipeline\Pipeline::Illuminate\Pipeline\{closure}
#23 /vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\Pipeline\Pipeline::then
#22 /vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(125): Illuminate\Queue\CallQueuedHandler::dispatchThroughMiddleware
#21 /vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(69): Illuminate\Queue\CallQueuedHandler::call
#20 /vendor/laravel/framework/src/Illuminate/Queue/Jobs/Job.php(98): Illuminate\Queue\Jobs\Job::fire
#19 /vendor/laravel/framework/src/Illuminate/Queue/Worker.php(429): Illuminate\Queue\Worker::process
#18 /vendor/laravel/framework/src/Illuminate/Queue/Worker.php(379): Illuminate\Queue\Worker::runJob
#17 /vendor/laravel/framework/src/Illuminate/Queue/Worker.php(173): Illuminate\Queue\Worker::daemon
#16 /vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(150): Illuminate\Queue\Console\WorkCommand::runWorker
#15 /vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(134): Illuminate\Queue\Console\WorkCommand::handle
#14 /vendor/laravel/horizon/src/Console/WorkCommand.php(51): Laravel\Horizon\Console\WorkCommand::handle
#13 /vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}
#12 /vendor/laravel/framework/src/Illuminate/Container/Util.php(41): Illuminate\Container\Util::unwrapIfClosure
#11 /vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\Container\BoundMethod::callBoundMethod
#10 /vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\Container\BoundMethod::call
#9 /vendor/laravel/framework/src/Illuminate/Container/Container.php(651): Illuminate\Container\Container::call
#8 /vendor/laravel/framework/src/Illuminate/Console/Command.php(139): Illuminate\Console\Command::execute
#7 /vendor/symfony/console/Command/Command.php(308): Symfony\Component\Console\Command\Command::run
#6 /vendor/laravel/framework/src/Illuminate/Console/Command.php(124): Illuminate\Console\Command::run
#5 /vendor/symfony/console/Application.php(998): Symfony\Component\Console\Application::doRunCommand
#4 /vendor/symfony/console/Application.php(299): Symfony\Component\Console\Application::doRun
#3 /vendor/symfony/console/Application.php(171): Symfony\Component\Console\Application::run
#2 /vendor/laravel/framework/src/Illuminate/Console/Application.php(102): Illuminate\Console\Application::run
#1 /vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(129): Illuminate\Foundation\Console\Kernel::handle
#0 /artisan(37): null
```

**Comment by frankdejonge** [comment]
This is most likely a race condition where multiple actions are initially not seeing a directory, then both trying to make it and only one succeeds. The other requests then fails because the directory already exists, leading to this exception.

**Comment by daanhaitsma** [comment]
Thanks for the quick fix! I'm working on the same issue as @NilsSlui, but unfortunately there it doesn't seem to be a race condition as the directory has sometimes existed for many years already.

I was hopeful that the second check you added would still help on this issue as well, so just updated flysystem but unfortunately the same error is still showing up "randomly".

Do you happen to know of anything else that could cause Flysystem to not detect that the directory exists already?

---

Just to paint a complete picture, here's exactly what we're doing:
* Have a Laravel SFTP disk:  `$this->disk = Storage::disk('disk-name');`
* Check if file exists: `if ($this->disk->exists($this->filePath)) {`
* Read the stream: `$this->disk->getDriver()->readStream($this->filePath);`
* Combine the existing stream with the new stream, then create or update the file: `$this->disk->put($this->filePath, $content);`

This sometimes succeeds and sometimes fails - with exception `UnableToCreateDirectory` - but after no more than two retries it always eventually succeeds.
