### ISSUE TITLE
AWS S3 Adapter V3 and Stream Filters

### ISSUE THREAD

**Issue by rcky** [thephpleague/flysystem#1598]
### Question

I tried to update the flysystem packages and noticed two unexpected behaviors (one might be related to the version of the S3/Minio storage). For completeness, we have to work with some base64 encoded content of Zip files which will usually not come from a file.

```php
$client = new Aws\S3\S3Client([
    'version' => 'latest',
    'region' => 'eu-central-1',
    'endpoint' => 'minio:9000',
    'use_path_style_endpoint' => true,
    'credentials' => [],
]);

$adapter = new AwsS3V3Adapter($client, 'test-service', '', null, new ExtensionMimeTypeDetector());
$operator = new Filesystem($adapter);

$readAdapter = new LocalFilesystemAdapter('.');
$readOperator = new Filesystem($readAdapter);
$stream = $readOperator->readStream('test.txt');
try {

    \stream_filter_append($stream, 'convert.base64-decode', STREAM_FILTER_READ);
    $operator->writeStream('test.txt', $stream);
} finally {
    \fclose($stream);
}
```
1. As soon as the input stream has a certain size, it takes ages to upload a file (mostly resulting in a process timeout). I was able to overcome this issue by using an intermediate temp stream and apply the filter on write. Nevertheless, I'd like to understand the problem.
2. This simple example results in a Bad Request Error: `XAmzContentSHA256Mismatch (client): The provided 'x-amz-content-sha256' header does not match what was computed.` I added [some stack traces](https://github.com/thephpleague/flysystem/issues/1598#issuecomment-1327317045)  (some of the names might differ).

| Q                 | A       |
|-------------------|---------|
| Flysystem Version | 3.10.3   |
| Adapter Name      | flysystem-aws-s3-v3 |
| Adapter version   | 3.10.3   |
| PHP version   | 8.0.10   |

**Edit:** Might be related to this https://github.com/aws/aws-sdk-php/issues/540

**Comment by rcky** [comment]
``` sh
Fatal error: Uncaught GuzzleHttp\Exception\ClientException: Client error: `PUT http://gav-service-minio:9000/gav-service/test.txt` resulted in a `400 Bad Request` response:
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>XAmzContentSHA256Mismatch</Code><Message>The provided &#39;x-amz-con (truncated...)
 in /app/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php:113
Stack trace:
#0 /app/vendor/guzzlehttp/guzzle/src/Middleware.php(69): GuzzleHttp\Exception\RequestException::create(Object(GuzzleHttp\Psr7\Request), Object(GuzzleHttp\Psr7\Response), NULL, Array, NULL)
#1 /app/vendor/guzzlehttp/promises/src/Promise.php(204): GuzzleHttp\Middleware::GuzzleHttp\{closure}(Object(GuzzleHttp\Psr7\Response))
#2 /app/vendor/guzzlehttp/promises/src/Promise.php(153): GuzzleHttp\Promise\Promise::callHandler(1, Object(GuzzleHttp\Psr7\Response), NULL)
#3 /app/vendor/guzzlehttp/promises/src/TaskQueue.php(48): GuzzleHttp\Promise\Promise::GuzzleHttp\Promise\{closure}()
#4 /app/vendor/guzzlehttp/guzzle/src/Handler/CurlMultiHandler.php(158): GuzzleHttp\Promise\TaskQueue->run()
#5 /app/vendor/guzzlehttp/guzzle/src/Handler/CurlMultiHandler.php(183): GuzzleHttp\Handler\CurlMultiHandler->tick()
#6 /app/vendor/guzzlehttp/promises/src/Promise.php(248): GuzzleHttp\Handler\CurlMultiHandler->execute(true)
#7 /app/vendor/guzzlehttp/promises/src/Promise.php(224): GuzzleHttp\Promise\Promise->invokeWaitFn()
#8 /app/vendor/guzzlehttp/promises/src/Promise.php(269): GuzzleHttp\Promise\Promise->waitIfPending()
#9 /app/vendor/guzzlehttp/promises/src/Promise.php(226): GuzzleHttp\Promise\Promise->invokeWaitList()
#10 /app/vendor/guzzlehttp/promises/src/Promise.php(269): GuzzleHttp\Promise\Promise->waitIfPending()
#11 /app/vendor/guzzlehttp/promises/src/Promise.php(226): GuzzleHttp\Promise\Promise->invokeWaitList()
#12 /app/vendor/guzzlehttp/promises/src/Promise.php(62): GuzzleHttp\Promise\Promise->waitIfPending()
#13 /app/vendor/aws/aws-sdk-php/src/S3/S3ClientTrait.php(35): GuzzleHttp\Promise\Promise->wait()
#14 /app/vendor/league/flysystem-aws-s3-v3/AwsS3V3Adapter.php(160): Aws\S3\S3Client->upload('gav-service', 'test.txt', Resource id #186, 'private', Array)
#15 /app/vendor/league/flysystem-aws-s3-v3/AwsS3V3Adapter.php(203): League\Flysystem\AwsS3V3\AwsS3V3Adapter->upload('test.txt', Resource id #186, Object(League\Flysystem\Config))
#16 /app/vendor/league/flysystem/src/Filesystem.php(69): League\Flysystem\AwsS3V3\AwsS3V3Adapter->writeStream('test.txt', Resource id #186, Object(League\Flysystem\Config))
#17 /app/tryout.php(35): League\Flysystem\Filesystem->writeStream('test.txt', Resource id #186)
#18 {main}

Next Aws\S3\Exception\S3Exception: Error executing "PutObject" on "//gav-service-minio:9000/gav-service/test.txt"; AWS HTTP error: Client error: `PUT http://gav-service-minio:9000/gav-service/test.txt` resulted in a `400 Bad Request` response:
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>XAmzContentSHA256Mismatch</Code><Message>The provided &#39;x-amz-con (truncated...)
 XAmzContentSHA256Mismatch (client): The provided 'x-amz-content-sha256' header does not match what was computed. - <?xml version="1.0" encoding="UTF-8"?>
<Error><Code>XAmzContentSHA256Mismatch</Code><Message>The provided &#39;x-amz-content-sha256&#39; header does not match what was computed.</Message><Key>test.txt</Key><BucketName>gav-service</BucketName><Resource>/gav-service/test.txt</Resource><RequestId>172ACC8203FFD188</RequestId><HostId>67e5e8ea-a5f3-4497-a3c9-8aa2cecfb6f9</HostId></Error> in /app/vendor/aws/aws-sdk-php/src/WrappedHttpHandler.php:195
Stack trace:
#0 /app/vendor/aws/aws-sdk-php/src/WrappedHttpHandler.php(97): Aws\WrappedHttpHandler->parseError(Array, Object(GuzzleHttp\Psr7\Request), Object(Aws\Command), Array)
#1 /app/vendor/guzzlehttp/promises/src/Promise.php(204): Aws\WrappedHttpHandler->Aws\{closure}(Array)
#2 /app/vendor/guzzlehttp/promises/src/Promise.php(169): GuzzleHttp\Promise\Promise::callHandler(2, Array, NULL)
#3 /app/vendor/guzzlehttp/promises/src/RejectedPromise.php(42): GuzzleHttp\Promise\Promise::GuzzleHttp\Promise\{closure}(Array)
#4 /app/vendor/guzzlehttp/promises/src/TaskQueue.php(48): GuzzleHttp\Promise\RejectedPromise::GuzzleHttp\Promise\{closure}()
#5 /app/vendor/guzzlehttp/guzzle/src/Handler/CurlMultiHandler.php(158): GuzzleHttp\Promise\TaskQueue->run()
#6 /app/vendor/guzzlehttp/guzzle/src/Handler/CurlMultiHandler.php(183): GuzzleHttp\Handler\CurlMultiHandler->tick()
#7 /app/vendor/guzzlehttp/promises/src/Promise.php(248): GuzzleHttp\Handler\CurlMultiHandler->execute(true)
#8 /app/vendor/guzzlehttp/promises/src/Promise.php(224): GuzzleHttp\Promise\Promise->invokeWaitFn()
#9 /app/vendor/guzzlehttp/promises/src/Promise.php(269): GuzzleHttp\Promise\Promise->waitIfPending()
#10 /app/vendor/guzzlehttp/promises/src/Promise.php(226): GuzzleHttp\Promise\Promise->invokeWaitList()
#11 /app/vendor/guzzlehttp/promises/src/Promise.php(269): GuzzleHttp\Promise\Promise->waitIfPending()
#12 /app/vendor/guzzlehttp/promises/src/Promise.php(226): GuzzleHttp\Promise\Promise->invokeWaitList()
#13 /app/vendor/guzzlehttp/promises/src/Promise.php(62): GuzzleHttp\Promise\Promise->waitIfPending()
#14 /app/vendor/aws/aws-sdk-php/src/S3/S3ClientTrait.php(35): GuzzleHttp\Promise\Promise->wait()
#15 /app/vendor/league/flysystem-aws-s3-v3/AwsS3V3Adapter.php(160): Aws\S3\S3Client->upload('gav-service', 'test.txt', Resource id #186, 'private', Array)
#16 /app/vendor/league/flysystem-aws-s3-v3/AwsS3V3Adapter.php(203): League\Flysystem\AwsS3V3\AwsS3V3Adapter->upload('test.txt', Resource id #186, Object(League\Flysystem\Config))
#17 /app/vendor/league/flysystem/src/Filesystem.php(69): League\Flysystem\AwsS3V3\AwsS3V3Adapter->writeStream('test.txt', Resource id #186, Object(League\Flysystem\Config))
#18 /app/tryout.php(35): League\Flysystem\Filesystem->writeStream('test.txt', Resource id #186)
#19 {main}
```
