### ISSUE TITLE
Flysystem FTP - how detect if ftp connection is working ?

### ISSUE THREAD

**Issue by ghost** [thephpleague/flysystem#204]
Hello,

howdetect if a connection with ftp working.

my problem is when the serveur ftp not working i have a bad message not godd for the user : 

```Fatal error: Uncaught exception 'RuntimeException' with message 'Could not connect to host: ftp.exemple.com, port:21' in /var/www/site01/libs/vendor/league/flysystem/src/Adapter/Ftp.php:75 Stack trace: #0 /var/www/site01/libs/vendor/league/flysystem/src/Adapter/AbstractFtpAdapter.php(361): League\Flysystem\Adapter\Ftp->connect() #1 /var/www/site01/libs/vendor/league/flysystem/src/Adapter/Ftp.php(233): League\Flysystem\Adapter\AbstractFtpAdapter->getConnection() #2 /var/www/site01/libs/vendor/league/flysystem/src/Adapter/AbstractFtpAdapter.php(333): League\Flysystem\Adapter\Ftp->getMetadata('...') #3 /var/www/site01/libs/vendor/league/flysystem/src/Filesystem.php(89): League\Flysystem\Adapter\AbstractFtpAdapter->has('...') #4 /var/www/site01/libs/functions.php(279): League\Flysystem\Filesystem->has('...') #5 /var/www/site01/libs/sendZipexemple.php(113): copieFiles(Array, Object(League\Flysystem\Filesystem), Object(League\Flysystem\Filesystem), '...') #6 {ma in /var/www/site01/libs/vendor/league/flysystem/src/Adapter/Ftp.php on line 75 

```

so how i can test the sucess ftp connection befaore send my files

thanks to u.

```

**Comment by fbm-static** [comment]
I just tried with the ftp cli client and it works fine, but on PHP it doesn't. Is there a more verbose message I can get on why it's not connecting?

**Comment by ychoucha** [comment]
+1
