### ISSUE TITLE
Metadata can't be parsed from item No such file or directory.' , not enough parts.

### ISSUE THREAD

**Issue by Smashmint** [thephpleague/flysystem#654]
I'm using flysystem through laravel (5.2), when trying to create a file with the FTP driver on a Synology NAS i'm getting the following error.

When the file already exists there is no error and the content is replaced.

```[2016-05-10 15:21:22] local.ERROR: exception 'RuntimeException' with message 'Metadata can't be parsed from item 'ftpd: file2.txt: No such file or directory.' , not enough parts.' in /home/vagrant/website/vendor/league/flysystem/src/Adapter/AbstractFtpAdapter.php:401
Stack trace:
#0 /home/vagrant/website/vendor/league/flysystem/src/Adapter/AbstractFtpAdapter.php(380): League\Flysystem\Adapter\AbstractFtpAdapter->normalizeUnixObject('ftpd: file2.txt...', '')
#1 /home/vagrant/website/vendor/league/flysystem/src/Adapter/Ftp.php(355): League\Flysystem\Adapter\AbstractFtpAdapter->normalizeObject('ftpd: file2.txt...', '')
#2 /home/vagrant/website/vendor/league/flysystem/src/Adapter/AbstractFtpAdapter.php(536): League\Flysystem\Adapter\Ftp->getMetadata('file2.txt')
#3 /home/vagrant/website/vendor/league/flysystem/src/Filesystem.php(54): League\Flysystem\Adapter\AbstractFtpAdapter->has('file2.txt')
#4 /home/vagrant/website/vendor/league/flysystem/src/Filesystem.php(95): League\Flysystem\Filesystem->has('file2.txt')
#5 /home/vagrant/website/vendor/laravel/framework/src/Illuminate/Filesystem/FilesystemAdapter.php(84): League\Flysystem\Filesystem->put('file2.txt', 'content', Array)
#6 [internal function]: Illuminate\Filesystem\FilesystemAdapter->put('file2.txt', 'content')
#7 /home/vagrant/website/vendor/laravel/framework/src/Illuminate/Filesystem/FilesystemManager.php(326): call_user_func_array(Array, Array)
#8 /home/vagrant/website/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(221): Illuminate\Filesystem\FilesystemManager->__call('put', Array)
#9 /home/vagrant/website/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(221): Illuminate\Filesystem\FilesystemManager->put('file2.txt', 'content')
#10 /home/vagrant/website/app/Http/Controllers/ClientController.php(30): Illuminate\Support\Facades\Facade::__callStatic('put', Array)
#11 /home/vagrant/website/app/Http/Controllers/ClientController.php(30): Illuminate\Support\Facades\Storage::put('file2.txt', 'content')
#12 [internal function]: App\Http\Controllers\ClientController->test(Object(Illuminate\Http\Request))
#13 /home/vagrant/website/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(80): call_user_func_array(Array, Array)
#14 /home/vagrant/website/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(146): Illuminate\Routing\Controller->callAction('test', Array)
#15 /home/vagrant/website/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(94): Illuminate\Routing\ControllerDispatcher->call(Object(App\Http\Controllers\ClientController), Object(Illuminate\Routing\Route), 'test')
#16 [internal function]: Illuminate\Routing\ControllerDispatcher->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#17 /home/vagrant/website/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(52): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#18 [internal function]: Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#19 /home/vagrant/website/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#20 /home/vagrant/website/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(96): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#21 /home/vagrant/website/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(54): Illuminate\Routing\ControllerDispatcher->callWithinStack(Object(App\Http\Controllers\ClientController), Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'test')
#22 /home/vagrant/website/vendor/laravel/framework/src/Illuminate/Routing/Route.php(174): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'App\\Http\\Contro...', 'test')
#23 /home/vagrant/website/vendor/laravel/framework/src/Illuminate/Routing/Route.php(140): Illuminate\Routing\Route->runController(Object(Illuminate\Http\Request))
#24 /home/vagrant/website/vendor/laravel/framework/src/Illuminate/Routing/Router.php(724): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#25 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#26 /home/vagrant/website/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(52): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#27 [internal function]: Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#28 /home/vagrant/website/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#29 /home/vagrant/website/vendor/laravel/framework/src/Illuminate/Routing/Router.php(726): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#30 /home/vagrant/website/vendor/laravel/framework/src/Illuminate/Routing/Router.php(699): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#31 /home/vagrant/website/vendor/laravel/framework/src/Illuminate/Routing/Router.php(675): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#32 /home/vagrant/website/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(246): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#33 [internal function]: Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#34 /home/vagrant/website/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(52): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#35 /home/vagrant/website/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(44): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#36 [internal function]: Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#37 /home/vagrant/website/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(136): call_user_func_array(Array, Array)
#38 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#39 /home/vagrant/website/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#40 [internal function]: Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#41 /home/vagrant/website/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#42 /home/vagrant/website/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(132): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#43 /home/vagrant/website/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(99): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#44 /home/vagrant/website/public/index.php(53): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#45 {main}  
[2016-05-10 15:21:22] local.ERROR: exception 'RuntimeException' with message 'Metadata can't be parsed from item 'ftpd: file2.txt: No such file or directory.' , not enough parts.' in /home/vagrant/website/vendor/league/flysystem/src/Adapter/AbstractFtpAdapter.php:401
Stack trace:
#0 /home/vagrant/website/vendor/league/flysystem/src/Adapter/AbstractFtpAdapter.php(380): League\Flysystem\Adapter\AbstractFtpAdapter->normalizeUnixObject('ftpd: file2.txt...', '')
#1 /home/vagrant/website/vendor/league/flysystem/src/Adapter/Ftp.php(355): League\Flysystem\Adapter\AbstractFtpAdapter->normalizeObject('ftpd: file2.txt...', '')
#2 /home/vagrant/website/vendor/league/flysystem/src/Adapter/AbstractFtpAdapter.php(536): League\Flysystem\Adapter\Ftp->getMetadata('file2.txt')
#3 /home/vagrant/website/vendor/league/flysystem/src/Filesystem.php(54): League\Flysystem\Adapter\AbstractFtpAdapter->has('file2.txt')
#4 /home/vagrant/website/vendor/league/flysystem/src/Filesystem.php(95): League\Flysystem\Filesystem->has('file2.txt')
#5 /home/vagrant/website/vendor/laravel/framework/src/Illuminate/Filesystem/FilesystemAdapter.php(84): League\Flysystem\Filesystem->put('file2.txt', 'content', Array)
#6 [internal function]: Illuminate\Filesystem\FilesystemAdapter->put('file2.txt', 'content')
#7 /home/vagrant/website/vendor/laravel/framework/src/Illuminate/Filesystem/FilesystemManager.php(326): call_user_func_array(Array, Array)
#8 /home/vagrant/website/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(221): Illuminate\Filesystem\FilesystemManager->__call('put', Array)
#9 /home/vagrant/website/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(221): Illuminate\Filesystem\FilesystemManager->put('file2.txt', 'content')
#10 /home/vagrant/website/app/Http/Controllers/ClientController.php(30): Illuminate\Support\Facades\Facade::__callStatic('put', Array)
#11 /home/vagrant/website/app/Http/Controllers/ClientController.php(30): Illuminate\Support\Facades\Storage::put('file2.txt', 'content')
#12 [internal function]: App\Http\Controllers\ClientController->test(Object(Illuminate\Http\Request))
#13 /home/vagrant/website/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(80): call_user_func_array(Array, Array)
#14 /home/vagrant/website/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(146): Illuminate\Routing\Controller->callAction('test', Array)
#15 /home/vagrant/website/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(94): Illuminate\Routing\ControllerDispatcher->call(Object(App\Http\Controllers\ClientController), Object(Illuminate\Routing\Route), 'test')
#16 [internal function]: Illuminate\Routing\ControllerDispatcher->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#17 /home/vagrant/website/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(52): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#18 [internal function]: Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#19 /home/vagrant/website/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#20 /home/vagrant/website/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(96): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#21 /home/vagrant/website/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(54): Illuminate\Routing\ControllerDispatcher->callWithinStack(Object(App\Http\Controllers\ClientController), Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'test')
#22 /home/vagrant/website/vendor/laravel/framework/src/Illuminate/Routing/Route.php(174): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'App\\Http\\Contro...', 'test')
#23 /home/vagrant/website/vendor/laravel/framework/src/Illuminate/Routing/Route.php(140): Illuminate\Routing\Route->runController(Object(Illuminate\Http\Request))
#24 /home/vagrant/website/vendor/laravel/framework/src/Illuminate/Routing/Router.php(724): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#25 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#26 /home/vagrant/website/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(52): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#27 [internal function]: Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#28 /home/vagrant/website/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#29 /home/vagrant/website/vendor/laravel/framework/src/Illuminate/Routing/Router.php(726): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#30 /home/vagrant/website/vendor/laravel/framework/src/Illuminate/Routing/Router.php(699): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#31 /home/vagrant/website/vendor/laravel/framework/src/Illuminate/Routing/Router.php(675): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#32 /home/vagrant/website/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(246): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#33 [internal function]: Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#34 /home/vagrant/website/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(52): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#35 /home/vagrant/website/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(44): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#36 [internal function]: Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure)
#37 /home/vagrant/website/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(136): call_user_func_array(Array, Array)
#38 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#39 /home/vagrant/website/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#40 [internal function]: Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#41 /home/vagrant/website/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#42 /home/vagrant/website/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(132): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#43 /home/vagrant/website/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(99): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#44 /home/vagrant/website/public/index.php(53): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#45 {main} ```

**Comment by frankdejonge** [comment]
@Smashmint Hi, you should be using the Ftpd adapter rather than the Ftp one.
