### ISSUE TITLE
FTP ssl problem

### ISSUE THREAD

**Issue by it-can** [thephpleague/flysystem#685]
Hi,

I am using Laravel 5.2 with the Storage adapter for connecting to a FTP server with SSL. I am getting this error and don't know why...

```
 [ErrorException]
  ftp_rawlist(): SSL read failed

PHP Fatal error:  Uncaught ErrorException: fclose(): supplied resource is not a valid stream resource in /home/test/public_html/vendor/league/flysystem/src/Adapter/Ftp.php:495
Stack trace:
#0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'fclose(): suppl...', '/home/test/...', 495, Array)
#1 /home/test/public_html/vendor/league/flysystem/src/Adapter/Ftp.php(495): fclose(Resource id #209)
#2 /home/test/public_html/vendor/league/flysystem/src/Adapter/Ftp.php(191): League\Flysystem\Adapter\Ftp->isConnected()
#3 /home/test/public_html/vendor/league/flysystem/src/Adapter/AbstractFtpAdapter.php(609): League\Flysystem\Adapter\Ftp->disconnect()
#4 [internal function]: League\Flysystem\Adapter\AbstractFtpAdapter->__destruct()
#5 {main}
  thrown in /home/test/public_html/vendor/league/flysystem/src/Adapter/Ftp.php on line 495
```

This is my config "config/filesystems.php":
```
'ftp' => [
            'driver'   => 'ftp',
            'host'     => env('FTP_SERVER'),
            'port'     => env('FTP_PORT'),
            'username' => env('FTP_USERNAME'),
            'password' => env('FTP_PASSWORD'),
            'passive'  => true,
            'ssl'      => true,
            'timeout'  => 30,
            'root'     => '/',
        ],
```

This is my code:
```
Storage::disk('ftp')->allFiles();
```

My config is correct and I tested it on 2 machines, both giving the same error... Before I used FuelPHP and never had any problems with FTP SSL...

**Comment by frankdejonge** [comment]
@it-can Hi, is there anything in the log files?

**Comment by it-can** [comment]
```
[2016-08-12 17:08:17] production.ERROR: ErrorException: ftp_rawlist(): SSL read failed in /home/test/public_html/vendor/league/flysystem/src/Adapter/Ftp.php:459
Stack trace:
#0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'ftp_rawlist(): ...', '/home/test/...', 459, Array)
#1 /home/test/public_html/vendor/league/flysystem/src/Adapter/Ftp.php(459): ftp_rawlist(Resource id #209, '-alnR ')
#2 /home/test/public_html/vendor/league/flysystem/src/Adapter/AbstractFtpAdapter.php(323): League\Flysystem\Adapter\Ftp->listDirectoryContents('', true)
#3 /home/test/public_html/vendor/league/flysystem/src/Filesystem.php(270): League\Flysystem\Adapter\AbstractFtpAdapter->listContents('', true)
#4 /home/test/public_html/vendor/laravel/framework/src/Illuminate/Filesystem/FilesystemAdapter.php(257): League\Flysystem\Filesystem->listContents('', true)
#5 /home/test/public_html/vendor/laravel/framework/src/Illuminate/Filesystem/FilesystemAdapter.php(270): Illuminate\Filesystem\FilesystemAdapter->files(NULL, true)
#6 /home/test/public_html/app/Console/Commands/test/Invoice.php(131): Illuminate\Filesystem\FilesystemAdapter->allFiles()
#7 /home/test/public_html/app/Console/Commands/test/Invoice.php(69): App\Console\Commands\test\Invoice->fetchFTP()
#8 [internal function]: App\Console\Commands\test\Invoice->handle()
#9 /home/test/public_html/bootstrap/cache/compiled.php(1257): call_user_func_array(Array, Array)
#10 /home/test/public_html/vendor/laravel/framework/src/Illuminate/Console/Command.php(169): Illuminate\Container\Container->call(Array)
#11 /home/test/public_html/vendor/symfony/console/Command/Command.php(256): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#12 /home/test/public_html/vendor/laravel/framework/src/Illuminate/Console/Command.php(155): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#13 /home/test/public_html/vendor/symfony/console/Application.php(794): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#14 /home/test/public_html/vendor/symfony/console/Application.php(186): Symfony\Component\Console\Application->doRunCommand(Object(App\Console\Commands\test\Invoice), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#15 /home/test/public_html/vendor/symfony/console/Application.php(117): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#16 /home/test/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(107): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#17 /home/test/public_html/artisan(35): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#18 {main}
```

**Comment by it-can** [comment]
I am using PureFTPD as my FTP server

**Comment by it-can** [comment]
This is in my FTP log:

```
Aug 15 10:45:39 ftp.example.com pure-ftpd: (?@xxx.xxx.xxx.xxx) [INFO] New connection from xxx.xxx.xxx.xxx
Aug 15 10:45:39 ftp.example.com pure-ftpd: (?@xxx.xxx.xxx.xxx) [DEBUG] Command [auth] [TLS]
Aug 15 10:45:39 ftp.example.com pure-ftpd: (?@xxx.xxx.xxx.xxx) [INFO] SSL/TLS: Enabled TLSv1/SSLv3 with ECDHE-ECDSA-AES128-GCM-SHA256, 128 secret bits cipher
Aug 15 10:45:39 ftp.example.com pure-ftpd: (?@xxx.xxx.xxx.xxx) [DEBUG] Command [pbsz] [0]
Aug 15 10:45:39 ftp.example.com pure-ftpd: (?@xxx.xxx.xxx.xxx) [DEBUG] Command [prot] [P]
Aug 15 10:45:39 ftp.example.com pure-ftpd: (?@xxx.xxx.xxx.xxx) [DEBUG] Command [user] [testuser]
Aug 15 10:45:39 ftp.example.com pure-ftpd: (?@xxx.xxx.xxx.xxx) [DEBUG] Command [pass] [<*>]
Aug 15 10:45:39 ftp.example.com pure-ftpd: (?@xxx.xxx.xxx.xxx) [INFO] testuser is now logged in
Aug 15 10:45:39 ftp.example.com pure-ftpd: (testuser@xxx.xxx.xxx.xxx) [DEBUG] Command [pasv] []
Aug 15 10:45:39 ftp.example.com pure-ftpd: (testuser@xxx.xxx.xxx.xxx) [DEBUG] Command [pwd] []
Aug 15 10:45:39 ftp.example.com pure-ftpd: (testuser@xxx.xxx.xxx.xxx) [DEBUG] Command [type] [A]
Aug 15 10:45:39 ftp.example.com pure-ftpd: (testuser@xxx.xxx.xxx.xxx) [DEBUG] Command [list] [-alnR ]
```

**Comment by frankdejonge** [comment]
@it-can have you tried the Ftpd adapter?

**Comment by it-can** [comment]
Ok will test the ftpd adapter

**Comment by it-can** [comment]
I get this error:

Driver [ftpd] is not supported.

**Comment by frankdejonge** [comment]
@it-can that looks like a Laravel issue. Ping: @taylorotwell, is Ftpd available from within Laravel?

**Comment by it-can** [comment]
I hacked a bit in the laravel source, but getting the same errors

**Comment by it-can** [comment]
Mmm very strange, seems to be an issue with the FTP server... When I test with this, it works...

http://test.rebex.net/

**Comment by it-can** [comment]
Yeah its very strange issue, with fuelphp no issues at all

**Comment by it-can** [comment]
Aah with Fuelphp and ssl it also gives the same error...

```
Uncaught exception Fuel\Core\PhpErrorException: ftp_nlist(): SSL read failed
Callstack:
#0 /test/fuel/core/bootstrap.php(103): Fuel\Core\Errorhandler::error_handler(2, 'ftp_nlist(): SS...', '/test...', 535)
#1 [internal function]: {closure}(2, 'ftp_nlist(): SS...', '/test...', 535, Array)
#2 /test/fuel/core/classes/ftp.php(535): ftp_nlist(Resource id #59, '/')
#3 /test/app/tasks/invoice.php(40): Fuel\Core\Ftp->list_files('/')
#4 /test/fuel/core/base56.php(37): Fuel\Tasks\Invoice->test()
#5 /test/fuel/packages/oil/classes/refine.php(108): call_fuel_func_array(Array, Array)
#6 [internal function]: Oil\Refine::run('\\Fuel\\Tasks\\Inv...', Array)
#7 /test/fuel/packages/oil/classes/command.php(126): call_user_func('Oil\\Refine::run', 'invoice:test', Array)
#8 /test/oil(78): Oil\Command::init(Array)
#9 {main}
```

**Comment by it-can** [comment]
I'll close this for now, when I find a solution I will post it here

**Comment by frankdejonge** [comment]
@it-can thanks for getting back to this 👍

**Comment by wassup-** [comment]
Any updates on this issue?

**Comment by RubtsovAV** [comment]
@wassup- Try this adapter https://github.com/vladimir-yuldashev/flysystem-curlftp

**Comment by pmartelletti** [comment]
@frankdejonge I'm  having the same issue - can I assume that if the SSL certificate it's expired, then this will fail?

**Comment by Jossnaz** [comment]
similar issue here

**Comment by Pchol** [comment]
I'm having the same issue if install php package from deb.sury.org (problem in libssl1.1 library). See https://github.com/oerdnj/deb.sury.org/issues/1185

**Comment by idhamhafidz** [comment]
Ok. Inside the configuration file like this:

'ftp' => [
    'driver' => 'ftp',
    'host' => 'ftp.example.com',
    'username' => 'your-username',
    'password' => 'your-password',
   'passive' => 'false',
   'ignorePassiveAddress' => true,
   'port' => 21,
]

and it works.
