### ISSUE TITLE
"Invalid argument" exception when using $fs->deleteDir() with S3 V2 and GCS

### ISSUE THREAD

**Issue by AssortedParrot** [thephpleague/flysystem#695]
I'm using the AWS S3 V2 adapter to connect to Google Cloud Storage. It seems to be working fine, I can create and modify files, but trying to delete a directory using `$fs->deleteDir()` throws an "invalid argument" exception.

This is the exception and the stack trace I'm getting:

```
 (Aws\S3\Exception\InvalidArgumentException) /var/websites/test/vendor/aws/aws-sdk-php/src/Aws/Common/Exception/NamespaceExceptionFactory.php line 91

 Invalid argument.

 #0 /var/websites/test/vendor/aws/aws-sdk-php/src/Aws/Common/Exception/NamespaceExceptionFactory.php(76): Aws\Common\Exception\NamespaceExceptionFactory->createException('Aws\\S3\\Exceptio...', Object(Guzzle\Http\Message\EntityEnclosingRequest), Object(Guzzle\Http\Message\Response), Array)
 #1 /var/websites/test/vendor/aws/aws-sdk-php/src/Aws/Common/Exception/ExceptionListener.php(55): Aws\Common\Exception\NamespaceExceptionFactory->fromResponse(Object(Guzzle\Http\Message\EntityEnclosingRequest), Object(Guzzle\Http\Message\Response))
 #2 [internal function]: Aws\Common\Exception\ExceptionListener->onRequestError(Object(Guzzle\Common\Event), 'request.error', Object(Symfony\Component\EventDispatcher\EventDispatcher))
 #3 /var/websites/test/app/cache/dev/classes.php(1858): call_user_func(Array, Object(Guzzle\Common\Event), 'request.error', Object(Symfony\Component\EventDispatcher\EventDispatcher))
 #4 /var/websites/test/app/cache/dev/classes.php(1773): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'request.error', Object(Guzzle\Common\Event))
 #5 /var/websites/test/vendor/guzzle/guzzle/src/Guzzle/Http/Message/Request.php(589): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('request.error', Object(Guzzle\Common\Event))
 #6 /var/websites/test/vendor/guzzle/guzzle/src/Guzzle/Http/Message/Request.php(378): Guzzle\Http\Message\Request->processResponse(Array)
 #7 /var/websites/test/vendor/guzzle/guzzle/src/Guzzle/Http/Message/EntityEnclosingRequest.php(49): Guzzle\Http\Message\Request->setState('complete', Array)
 #8 /var/websites/test/vendor/guzzle/guzzle/src/Guzzle/Http/Curl/CurlMulti.php(303): Guzzle\Http\Message\EntityEnclosingRequest->setState('complete', Array)
 #9 /var/websites/test/vendor/guzzle/guzzle/src/Guzzle/Http/Curl/CurlMulti.php(257): Guzzle\Http\Curl\CurlMulti->processResponse(Object(Guzzle\Http\Message\EntityEnclosingRequest), Object(Guzzle\Http\Curl\CurlHandle), Array)
 #10 /var/websites/test/vendor/guzzle/guzzle/src/Guzzle/Http/Curl/CurlMulti.php(240): Guzzle\Http\Curl\CurlMulti->processMessages()
 #11 /var/websites/test/vendor/guzzle/guzzle/src/Guzzle/Http/Curl/CurlMulti.php(224): Guzzle\Http\Curl\CurlMulti->executeHandles()
 #12 /var/websites/test/vendor/guzzle/guzzle/src/Guzzle/Http/Curl/CurlMulti.php(111): Guzzle\Http\Curl\CurlMulti->perform()
 #13 /var/websites/test/vendor/guzzle/guzzle/src/Guzzle/Http/Curl/CurlMultiProxy.php(94): Guzzle\Http\Curl\CurlMulti->send()
 #14 /var/websites/test/vendor/guzzle/guzzle/src/Guzzle/Http/Client.php(284): Guzzle\Http\Curl\CurlMultiProxy->send()
 #15 /var/websites/test/vendor/aws/aws-sdk-php/src/Aws/Common/Client/AbstractClient.php(256): Guzzle\Http\Client->send(Object(Guzzle\Http\Message\EntityEnclosingRequest))
 #16 /var/websites/test/vendor/guzzle/guzzle/src/Guzzle/Service/Client.php(136): Aws\Common\Client\AbstractClient->send(Object(Guzzle\Http\Message\EntityEnclosingRequest))
 #17 /var/websites/test/vendor/guzzle/guzzle/src/Guzzle/Service/Command/AbstractCommand.php(153): Guzzle\Service\Client->execute(Object(Aws\S3\Command\S3Command))
 #18 /var/websites/test/vendor/aws/aws-sdk-php/src/Aws/S3/Model/DeleteObjectsTransfer.php(114): Guzzle\Service\Command\AbstractCommand->execute()
 #19 /var/websites/test/vendor/guzzle/guzzle/src/Guzzle/Batch/Batch.php(59): Aws\S3\Model\DeleteObjectsTransfer->transfer(Array)
 #20 /var/websites/test/vendor/guzzle/guzzle/src/Guzzle/Batch/AbstractBatchDecorator.php(44): Guzzle\Batch\Batch->flush()
 #21 /var/websites/test/vendor/guzzle/guzzle/src/Guzzle/Batch/NotifyingBatch.php(33): Guzzle\Batch\AbstractBatchDecorator->flush()
 #22 /var/websites/test/vendor/guzzle/guzzle/src/Guzzle/Batch/ExceptionBufferingBatch.php(22): Guzzle\Batch\NotifyingBatch->flush()
 #23 /var/websites/test/vendor/guzzle/guzzle/src/Guzzle/Batch/AbstractBatchDecorator.php(44): Guzzle\Batch\ExceptionBufferingBatch->flush()
 #24 /var/websites/test/vendor/aws/aws-sdk-php/src/Aws/S3/Model/ClearBucket.php(173): Guzzle\Batch\AbstractBatchDecorator->flush()
 #25 /var/websites/test/vendor/aws/aws-sdk-php/src/Aws/S3/S3Client.php(666): Aws\S3\Model\ClearBucket->clear()
 #26 /var/websites/test/vendor/league/flysystem-aws-s3-v2/src/AwsS3Adapter.php(299): Aws\S3\S3Client->deleteMatchingObjects('my-bucket', 'folder/subfolder...')
 #27 /var/websites/test/vendor/league/flysystem/src/Filesystem.php(250): League\Flysystem\AwsS3v2\AwsS3Adapter->deleteDir('folder/subfolder...')
 #28 /var/websites/test/src/AppBundle/FilesystemHelper->deleteDir('folder/subfolder...')
 #29 /var/websites/test/src/AppBundle/Controller/FilesystemController.php(101): AppBundle\FilesystemHelper->updateDirectory(Object(AppBundle\Entity\Directory))
 #30 [internal function]: AppBundle\Controller\FilesystemController->updateDirAction(Object(Symfony\Component\HttpFoundation\Request))
 #31 /var/websites/test/app/bootstrap.php.cache(3238): call_user_func_array(Array, Array)
 #32 /var/websites/test/app/bootstrap.php.cache(3197): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1)
 #33 /var/websites/test/app/bootstrap.php.cache(3351): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
 #34 /var/websites/test/app/bootstrap.php.cache(2536): Symfony\Component\HttpKernel\DependencyInjection\ContainerAwareHttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
 #35 ./app_dev.php(29): Symfony\Component\HttpKernel\Kernel->handle(Object(Symfony\Component\HttpFoundation\Request))
 #36 {main}
```

What could be causing this, and how can I fix/work around it?

**Comment by brytey2k** [comment]
Having this same problem.... any fix yet??

**Comment by frankdejonge** [comment]
The problem here is that GCS does not follow S3 protocol correctly, this is not fixable through Flysystem.
